Script selection menu & optional proxy deployment
ElrondNetwork/elrond-go-scripts-mainnet pull request #18
Opened 2020-09-18 07:40 UTC by valentin-lup

2020-09-18 08:19 UTC, iulianpascalau commented on script.sh
> +  NUMBEROFNODES=4
It's ok this hardcoded value for now. Can we have this value as an extra option with the default value of 4?

2020-09-18 08:19 UTC, iulianpascalau commented on script.sh
> +         if [[ "$INDEX" == 3 ]]; then
might change to 0 as to work with unlimited number of observers

2020-09-18 08:19 UTC, iulianpascalau commented on script.sh
> +done
Please add an extra line here

2020-09-18 08:45 UTC, iulianpascalau reviewed
Would

2020-09-18 08:45 UTC, iulianpascalau commented on script.sh
> +echo -e "${GREEN}1) ${CYAN}install${GREEN} - Regular install process for validator nodes${NC}"
Would have been nice for another option: "Auto-prepare variables.cfg" in which would have auto-populate the user name and home folder by itself (also strongly requested by our community)

2020-09-18 08:55 UTC, iulianpascalau commented on script.sh
> +echo -e "${GREEN}1) ${CYAN}install${GREEN} - Regular install process for validator nodes${NC}"
Also, a new option for generating (and saving a new pem file)

2020-09-18 11:13 UTC, iulianpascalau requested changes

2020-09-18 11:13 UTC, iulianpascalau commented on script.sh
> +echo -e "${GREEN}3) ${CYAN}upgrade${GREEN} - Run the upgrade process for the installed nodes${NC}"
This, apparently, doesn't work as it states: "You do not have the latest version of the elrond-go-scripts-mainnet !!!
Please run ./script.sh github_pull before running the upgrade command...". Even after trying a `github_pull` command.

2020-09-18 11:26 UTC, valentin-lup commented on script.sh
> +         if [[ "$INDEX" == 3 ]]; then
Noted !

2020-09-18 11:26 UTC, valentin-lup commented on script.sh
> +  NUMBEROFNODES=4
Good idea ! Will change.

2020-11-02 09:12 UTC, andreibancioiu commented on script.sh
> +echo -e "${GREEN}3) ${CYAN}upgrade${GREEN} - Run the upgrade process for the installed nodes${NC}"
Could be because:

```
CURRENT_SCRIPTS_COMMIT=$(git show | grep commit | awk '{print $2}')
```

is influenced by commits that contain the word `commit` in themselves, or that contain the word `commit` within their diff summary.

Perhaps we can add a `-m 1` option to the `grep`?

```
CURRENT_SCRIPTS_COMMIT=$(git show | grep -m 1 commit | awk '{print $2}')
```

2020-11-03 15:48 UTC, valentin-lup commented on script.sh
> +  NUMBEROFNODES=4
After discussing it we'll stick to the 4 observers for now.

2020-11-03 15:49 UTC, valentin-lup commented on script.sh
> +echo -e "${GREEN}1) ${CYAN}install${GREEN} - Regular install process for validator nodes${NC}"
Reverted for now but will keep in mind.

2020-11-03 15:49 UTC, valentin-lup commented on script.sh
> +echo -e "${GREEN}3) ${CYAN}upgrade${GREEN} - Run the upgrade process for the installed nodes${NC}"
Fixed this in current pull request !

2020-11-03 15:50 UTC, closed without merging