Updated scripts with a selection menu and included some fixes.
ElrondNetwork/elrond-go-scripts-mainnet pull request #21
Opened 2020-11-19 08:34 UTC by valentin-lup

Updated scripts with a selection menu and included some fixes

2020-11-20 08:08 UTC, andreibancioiu reviewed
:+1: :tada: 

Will :evergreen_tree: after manual testing.

2020-11-20 08:08 UTC, andreibancioiu commented on config/functions.cfg
> +
@iulianpascalau, now I see:

```
git checkout --force $BINARYVER
```

... for the **elrond-go** repository, which is fine.

@valentin-lup, therefore, is the following line still required?

```
curl --silent "https://api.github.com/repos/ElrondNetwork/elrond-go/releases/latest" > $HOME/api_check_tmp
```

2020-11-20 09:44 UTC, iulianpascalau reviewed
Will approve after testing

2020-11-20 09:44 UTC, iulianpascalau commented on config/menu_functions.cfg
> +            sudo systemctl daemon-reload
Interesting, maybe we can call this on each `start` function? It happens that sometimes I do a custom change in the .service file and each time I have to call a `sudo systemctl daemon-reload`

2020-11-20 09:44 UTC, iulianpascalau commented on script.sh
>  #Color to the people
Color definition * ? (Uncle Bob: Don't try to be funny :D )

2020-11-20 11:57 UTC, iulianpascalau requested changes

2020-11-20 11:57 UTC, iulianpascalau commented on script.sh
> +#RED='\x1B[0;31m'
uncomment these color definitions?

2020-11-20 12:41 UTC, iulianpascalau commented on config/menu_functions.cfg
> +               echo -e "${RED}Warning! The nodes will not be automatically restarted after the DB is removed!${NC}"
maybe standardize the message output? On upgrade we have
```
--> elrond-node-0 upgraded. Don't forget to start it...

```

2020-11-20 20:38 UTC, valentin-lup commented on config/menu_functions.cfg
> +            sudo systemctl daemon-reload
too many of those and you'd get an "Excess arguments." error... so I'd rather not abuse it...

2020-11-20 20:39 UTC, valentin-lup commented on script.sh
> +#RED='\x1B[0;31m'
Will do !

2020-11-20 20:42 UTC, valentin-lup commented on script.sh
>  #Color to the people
Ok... you're no fun...

2020-11-20 20:45 UTC, valentin-lup commented on config/functions.cfg
> +
Needed. Prevents errors in case people don't use github tokens but "abuse" the scripts...

2020-11-23 08:04 UTC, andreibancioiu approved these changes

2020-11-23 08:11 UTC, iulianpascalau commented on config/functions.cfg
> +RED='\x1B[0;31m'
double (event triple on some values) definition of the same variables. This is generally a bad practice. Why not defining them in variables.sh (since that file is sourced just about everywhere)? Or another file like `defaults.cfg`?

2020-11-23 08:46 UTC, valentin-lup commented on config/functions.cfg
> +RED='\x1B[0;31m'
That was a facepalm moment. Fixed !

2020-11-23 08:51 UTC, iulianpascalau approved these changes

2020-11-23 08:53 UTC, merged